In [1]:
import numpy as np
import sys

In [2]:
#Background info
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [3]:
b=np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [4]:
#get Dimension
a.ndim

1

In [5]:
b.ndim

2

In [6]:
#Get shape
a.shape

(3,)

In [7]:
b.shape

(2, 3)

In [8]:
# Get type
a.dtype

dtype('int32')

In [9]:
#Get size
a.itemsize
b.itemsize

8

In [10]:
# Get total size
a.size * a.itemsize

12

In [11]:
a.nbytes

12

In [12]:
a= np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14,]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [13]:
#Getspecific element [r,c]
#a[1,-2]
a[1,5]

13

In [14]:
#Get a specific row 
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [15]:
# get a specific column 
a[:,2]

array([ 3, 10])

In [16]:
#Geting a little fancy[startindex:endindex:stepsize]
a[0, 1:6:1]

array([2, 3, 4, 5, 6])

In [17]:
a[1,5]=20
print(a)


a[:,2]=[1,2]
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [18]:
b=np.array([[[1,2],[3,4],[5,6],[7,8]]])
print (b)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [20]:
#Accesing of rows
b[:,1,:]

array([[3, 4]])

In [21]:
#Initialization

#All zero matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [23]:
#any other number
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [24]:
np.full(a.shape,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [25]:
#random deciml numbers
np.random.rand(4,2)

array([[0.38408956, 0.99726143],
       [0.91095905, 0.48285167],
       [0.62935238, 0.63201967],
       [0.25598048, 0.0928572 ]])

In [26]:
#random deciml numbers
np.random.sample(a.shape)

array([[0.01617217, 0.8141459 , 0.85720212, 0.7116479 , 0.96220882,
        0.91291683, 0.53447767],
       [0.50017735, 0.44401408, 0.55571596, 0.33782581, 0.2120698 ,
        0.92494546, 0.89242602]])

In [28]:
#random integer numbers
np.random.randint(-4,8, size=(3,3))

array([[ 7,  7,  2],
       [-3,  7,  3],
       [ 1,  3,  6]])

In [29]:
# the identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [32]:
#Repeat an array
arr=np.array([[1,2,3]])
r1=np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [36]:
output=np.ones((5,5))
print(output)

z=np.zeros((3,3))
z[1,1]=9
print(z)

output[1:4,1:4]=z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### be careful when copying array

In [39]:
a=np.array([1,2,3])
b=a.copy()
b[0]= 100

print(a)

[1 2 3]


In [40]:
#mathematics
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [41]:
a + 2

array([3, 4, 5, 6])

In [43]:
a - 2

array([-1,  0,  1,  2])

In [44]:
a * 2

array([2, 4, 6, 8])

In [45]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [46]:
b=np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [48]:
#take the sin , cos, tan
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [49]:
#Linear algebra
a=np.ones((2,3))
print(a)

b=np.full((3,2),2)
print (b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [50]:
#find the determinant
c=np. identity(3)
np.linalg.det(c)

1.0

In [51]:
# https://docs.scipy.org/doc/numpy/refrence/routines.linalg.html

In [52]:
stats= np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [53]:
np.min(stats )

1

In [54]:
np.max(stats)

6

In [55]:
np.min  (stats, axis=1)

array([1, 4])

In [56]:
np.max  (stats, axis=1)

array([3, 6])

In [57]:
#REorganizing arrays 
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after=before.reshape((2,2,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [58]:
#Vertically stacking vectors
v1= np.array([1,2,3,4])
v2= np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [60]:
#Horizontal stack
h1= np.ones((2,4))
h2= np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [61]:
#np.genfromtext('data.txt',delimiter',')
#filedata = filedata.astype('int32')
#filedata